// Re-export dashboard types from shared-types for convenience
export type {
  NetWorthResponse,
  AssetsByType,
  LiabilitiesByType,
  NetWorthProjection,
  AssetBreakdown,
  LiabilityBreakdown,
  LoansResponse,
  LoanSummary,
  LoanDetail,
  LoanAmortizationResponse,
  AmortizationEntry,
  InvestmentsResponse,
  InvestmentPortfolioSummary,
  InvestmentHoldingSummary,
  // Scenario types
  Scenario,
  ScenarioOverride,
  OverrideTargetType,
  CreateScenarioDto,
  UpdateScenarioDto,
  CreateScenarioOverrideDto,
  ScenarioProjectionResponse,
  ScenarioComparisonResponse,
  ScenarioComparisonItem,
  YearlyProjectionSnapshot,
  ProjectionSummary,
} from '@finance-app/shared-types'
